<?php
/**
 * Created by PhpStorm.
 * User: jialiang3
 * Date: 2018/2/1
 * Time: 下午3:38
 */

interface  NodeInterface{

    public function addNode(NodeInterface $node);

    public function listNode();

    public function isSite();

}

class BaseNode implements NodeInterface{
    protected $nodes = [];

    protected $name;

    protected $isSite = false;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function addNode(NodeInterface $node)
    {
        return array_push($this->nodes, $node);
    }

    public function listNode()
    {
        foreach ($this->nodes as $node){
            echo ($node->isSite() ? '-' : ".") . $node->name . "\n";
            $node->listNode();
        }
        //return $this->nodes;
    }

    public function isSite(){
        return $this->isSite;
    }
}


class Site extends  BaseNode{
    protected $name;
    protected $isSite = true;

    public function addNode(NodeInterface $node)
    {
        return parent::addNode($node); // TODO: Change the autogenerated stub
    }
}

class Column extends  BaseNode{
    protected $name;
    protected $isSite =false;
    public function addNode(NodeInterface $node)
    {
       if($node->isSite())throw new Exception("column can not add SiteNode");
       parent::addNode($node);
    }
}


class Test{
    public function __invoke()
    {
        $root = new Site('Root');
        $fashionSite = new Site("fashion.sina.com.cn");
        $fashionSite->addNode(new Column("美妆"));
        $fashionSite->addNode(new Column("女性"));

        $sportSite = new Site("sports.sina.com.cn");
        $footballColumn = new Column("足球");
        $footballColumn->addNode(new Column("中超"));
        $footballColumn->addNode(new Column("西甲"));
        $sportSite->addNode($footballColumn);


        $root->addNode($fashionSite);
        $root->addNode($sportSite);
        $root->addNode(new Column("目录"));

        $root->listNode();
        $sportSite->listNode();
        // TODO: Implement __invoke() method.
    }
}
$test = new Test();
$test();